---
title: "Analise de Retorno de Linhas de Onibus na Cidade do Rio de Janeiro"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(plotly)
library(ggplot2)
library(sf)
library(readr)
library(janitor)
library(rgdal)
library(readxl)
library(writexl)
library(tidyverse)
library(geobr)


# carregando dados
# Importando o mapa da linhas retornadas
caminho_arquivo <- "mapa.shp"
dados_shapefile <- suppressMessages(st_read(dsn = caminho_arquivo, quiet = TRUE))

# Baixando mapa de bairros do Bairros do Rio
bairros_rj = read_neighborhood() %>% filter(name_muni == 'Rio De Janeiro')


# Dados do segundo mapa
base = read_csv2('linha_reactive.csv') %>% clean_names()

resultado = inner_join(dados_shapefile, base, by = c("servico" = "linha_servico"))



# baixando dados de linhas reativadas
#linhas_reativadas = read_csv2('linha_reactive.csv') %>% clean_names()

# Juntando as basess
#resultado <- inner_join(linhas_reativadas, dados_shapefile, by = c("linha_servico" = "servico"))

# Criando coluna com um unico valor para substituir depois
dados_shapefile$retorno_linha <- "Linha Fixa"

# linhas
valores_retornado <- c("10", "12", "14", "104", "157", "201", "229", "254", "277", "301", "311", "349", "388", "435", "448", "518", "519", "603", "605", "626", "651", "652", "669", "678", "702", "709", "741", "743", "753", "757", "778", "785", "808", "809", "817", "822", "825", "830", "831", "833", "842", "845", "849", "851", "865", "870", "871", "880", "881", "885", "892", "893", "899", "901", "915", "921", "922", "925", "928", "951", "987", "990", "SP852", "SV669", "SV692", "SV831", "SV899", "SV922", "SVA665", "SVB665", "SVB685", "SVB901")

# Tratando para reconhecer linhas
dados_shapefile$retorno_linha[dados_shapefile$servico %in% valores_retornado] <- "Linha Retornada"


library(DT)

tabela_linhas = resultado %>% select(ap, origem_x_destino, servico, destino, direcao)%>%   rename(
    `Área de Planejamento` = ap,
    `Direção` = direcao,
    `Destino` = destino,
    `Servico` = servico,
    `Origem x Destino` = origem_x_destino
  ) %>% filter(`Área de Planejamento` != 'AP1')



```
Mapeamento de Linhas de ônibus {data-orientation=columns}
=================




Column {.tabset}
-----------------------------------------------------------------------

### Mapa de trajeto de linhas Retomadas

```{r}



renderPlotly({
  p <- ggplot() +
    geom_sf(data = bairros_rj, aes(geometry = geom), col = 'black', alpha = 0.5, size = 0.5) +
    geom_sf(data = dados_shapefile, aes(geometry = geometry, color = retorno_linha)) +
    labs(title = "Mapa de Linhas de Ônibus na Cidade do Rio de Janeiro - Retorno de Linhas Municipais", color = "Retorno de Linha", subtitle = 'Fonte: Data.rio') +
    scale_color_manual(values = c('#8d2036', 'green')) +  # Define colors manually
    theme_void() +
    theme(
      plot.title = element_text(family = "Arial", size = 18, face = "bold", hjust = 0.5),  # Title configuration
      plot.subtitle = element_text(family = "Arial", size = 14, face = "italic", hjust = 0.5),  # Subtitle configuration
      axis.title = element_text(family = "Arial", size = 12, face = "bold"),  # Axis title configuration
      axis.text = element_text(family = "Arial", size = 10),  # Axis text configuration
      legend.title = element_text(family = "Arial", size = 12, face = "bold"),  # Legend title configuration
      legend.text = element_text(family = "Arial", size = 10)  # Legend text configuration
    )
  
p <- ggplotly(p, tooltip = "retorno_linha") %>% 
  style(line = list(width = 0.4))
  
  # Add name_neighborhood as a column in the tooltip
})
```



Linhas Retomadas {data-orientation=columns}
=================

column {.sideBar data-width=100}
----------------------------------------
```{r}
selectInput("servico", "Selecione as Linhas:", choices = unique(tabela_linhas$Servico), multiple = TRUE, selected = unique(tabela_linhas$Servico))

selectInput("areaPlanejamento", "Selecione as Áreas de Planejamento:", 
              choices = unique(tabela_linhas$`Área de Planejamento`), 
              multiple = TRUE,
              selected = unique(tabela_linhas$`Área de Planejamento`))
```

Column {.tabset}
-----------------------------------------------------------------------

### Mapa de Linhas Municipais com Funcionamento Retomado

```{r}

renderPlotly({
  # req garante que a entrada tem um valor antes de prosseguir
  req(input$servico)

  # Filtrar tabela_linhas com base na entrada do usuário
  filtered_tabela_linhas <- tabela_linhas %>% filter(Servico %in% input$servico, `Área de Planejamento` %in% input$areaPlanejamento)
  
p <- ggplot() +
    geom_sf(data = bairros_rj, aes(geometry = geom), fill = '#F0F0F0', color = '#A9A9A9', alpha = 0.9, size = 0.2) +
    geom_sf(data = filtered_tabela_linhas, aes(geometry = geometry, color = filtered_tabela_linhas$`Área de Planejamento`,
                                      text = paste('Área de Planejamento: ', filtered_tabela_linhas$`Área de Planejamento`,
                             '<br>Nome da Linha: ', filtered_tabela_linhas$Servico, '<br>Direção: ', filtered_tabela_linhas$Direção))) +
    
    labs(title = "Linhas de Onibus retornadas na Cidade do Rio de Janeiro - Por Área de Planejamento", color = "Área de Planejamento do trajeto", subtitle = 'Fonte: Data.rio') +
    scale_color_manual(values = c('#ffb727', 'green', '#0000FF', '#8A2BE2', '#7FFF00', '#D2691E', '#FF7F50', '#6495ED', '#FFF8DC', '#DC143C', '#00FFFF', '#00008B', '#008B8B', '#B8860B'))+
    theme_void() +
    theme(
  # background color
      plot.title = element_text(family = "Arial", size = 18, face = "bold", hjust = 0.5, color = '#333333'),  # Title configuration
      plot.subtitle = element_text(family = "Arial", size = 14, face = "italic", hjust = 0.5, color = '#666666'),  # Subtitle configuration
      legend.title = element_text(family = "Arial", size = 12, face = "bold", color = '#333333'),  # Legend title configuration
      legend.text = element_text(family = "Arial", size = 10, color = '#666666')  # Legend text configuration
    )
  
p <- ggplotly(p, tooltip = 'text') %>% 
    style(line = list(width = 0.4)) 

})


```



### Linhas Retomadas

```{r}


datatable(tabela_linhas, options = list(pageLength = 20))
```


```{r}

```

